name: mimic3_safedrug

paths:
  diagnoses: data/raw/MIMIC-III/DIAGNOSES_ICD.csv
  procedures: data/raw/MIMIC-III/PROCEDURES_ICD.csv
  medications: data/raw/MIMIC-III/PRESCRIPTIONS.csv
  RXCUI2atc4: data/raw/MIMIC-III/RXCUI2atc4.csv
  ndc2RXCUI: data/raw/MIMIC-III/ndc2RXCUI.txt
  drug2atc: data/raw/MIMIC-III/drug-atc_safedrug.csv
  ddi: data/raw/MIMIC-III/drug-DDI_safedrug.csv
  idx2drug: data/raw/MIMIC-III/idx2drug.pkl

kwargs:
  diagnoses: {low_memory: False, dtype: {ICD9_CODE: category}}
  procedures: {low_memory: False, dtype: {ICD9_CODE: category}}
  medications: {low_memory: False, dtype: {NDC: category}}